<%@ Page Title="分类管理" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="CategoryMaster.aspx.cs" Inherits="Admin_CategoryMaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
  <a href="CategoryMaster.aspx">分类管理</a>
  <br />
  <br />
  <a href="SupplierMaster.aspx">供应商管理</a>
  <br />
  <br />
  <a href="ProductMaster.aspx">商品管理</a>
  <br />
  <br />
  <a href="OrderMaster.aspx">订单管理</a>
  <br />
  <br />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
  <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" DeleteMethod="DeleteCategory" InsertMethod="InSertCategory" SelectMethod="GetAllCategory" TypeName="MyPetShop.BLL.CategoryService" UpdateMethod="UpdateCategory">
    <DeleteParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </InsertParameters>
    <UpdateParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </UpdateParameters>
  </asp:ObjectDataSource>
  <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="ObjectDataSource1" DataKeyNames="CategoryId" AutoGenerateRows="false" AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateDeleteButton="true"
    AllowPaging="true"  OnItemDeleting="DetailsView1_ItemDeleting">
    <Fields>
      <asp:BoundField HeaderText="分类ID" DataField="CategoryId" Visible="false" />
      <asp:BoundField HeaderText="分类名称" DataField="Name" />
      <asp:BoundField HeaderText="分类描述" DataField="Descn" />
    </Fields>
  </asp:DetailsView>
  <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" runat="Server">
</asp:Content>


